spring.application.name=Mausam
weather.api.key=${Your_API_Key}
weather.api.baseUrl=https://api.openweathermap.org/data/2.5/weather
server.port=8080
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
